[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "in_d demo site"
authors = [{name = "Mike Parr-Burman", email = "2691690p@student.gla.ac.uk"}]
dynamic = ["version", "description"]
